export const SELECTED_SERIES = 'SELECTED_SERIES';
export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES';
export const RANDOM_TV_SERIES = 'RANDOM_TV_SERIES';
export const UPDATE_FAVOURITE_SERIES = 'UPDATE_FAVOURITE_SERIES';